services:
  - type: web
    name: contextwizard-backend
    runtime: docker
    repo: https://github.com/fikulasyon/contextwizard
    branch: main
    rootDir: backend
    plan: free
    region: frankfurt
    envVars:
      - key: LLM_PROVIDER
        value: perplexity
      - key: GEMINI_API_KEY
        sync: false
      - key: PERPLEXITY_API_KEY
        sync: false
      - key: PORT
        value: 8000

  - type: web
    name: contextwizard-probot
    runtime: docker
    repo: https://github.com/fikulasyon/contextwizard
    branch: main
    rootDir: probot-app
    plan: free
    region: frankfurt
    envVars:
      - key: APP_ID
        sync: false
      - key: WEBHOOK_SECRET
        sync: false
      - key: PRIVATE_KEY
        sync: false
      - key: BACKEND_URL
        fromService:
          name: contextwizard-backend
          type: web
          property: host
