services:
  # --- SERVICE BACKEND ---
  - type: web
    name: contextwizard-backend
    runtime: docker
    repo: https://github.com/fikulasyon/contextwizard
    branch: clean-code+deploy
    # On définit la racine du projet comme contexte de build
    rootDir: .
    # Chemin relatif depuis la racine
    dockerfilePath: backend/Dockerfile
    plan: free
    region: frankfurt
    envVars:
      - key: LLM_PROVIDER
        value: perplexity
      - key: GEMINI_API_KEY
        sync: false
      - key: PERPLEXITY_API_KEY
        sync: false
      - key: PORT
        value: 8000

  # --- SERVICE PROBOT ---
  - type: web
    name: contextwizard-probot
    runtime: docker
    repo: https://github.com/fikulasyon/contextwizard
    branch: clean-code+deploy
    # On définit également la racine ici
    rootDir: .
    # Chemin relatif depuis la racine
    dockerfilePath: probot-app/Dockerfile
    plan: free
    region: frankfurt
    envVars:
      - key: APP_ID
        sync: false
      - key: WEBHOOK_SECRET
        sync: false
      - key: PRIVATE_KEY
        sync: false
      - key: BACKEND_URL
        fromService:
          name: contextwizard-backend
          type: web
          property: host
